# Generated by Django 5.0 on 2023-12-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('BRA', 'Brasil'), ('ING', 'Inglaterra'), ('ARG', 'Argentina')], max_length=100, null=True)),
            ],
        ),
    ]
