# Generated by Django 5.0 on 2024-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atores', '0003_alter_ator_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='nacionalidade',
            field=models.CharField(blank=True, choices=[('EUA', 'Estados Unidos'), ('BRA', 'Brasil'), ('ING', 'Inglaterra'), ('ARG', 'Argentina'), ('GER', 'Alemanha'), ('AUS', 'Austrália'), ('HOL', 'Holanda'), ('ESP', 'Espanha'), ('FRA', 'França')], max_length=100, null=True),
        ),
    ]
